// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRI1IzahyYQ0Ug_HwdW0UZ7hGPkc3AalQ',
    appId: '1:699728181193:web:b4238ab7f4f74aa71ada18',
    messagingSenderId: '699728181193',
    projectId: 'chat-app-63df9',
    authDomain: 'chat-app-63df9.firebaseapp.com',
    storageBucket: 'chat-app-63df9.appspot.com',
    measurementId: 'G-C82PWWY2QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyG883jOfKA-pHtLQSPuKrT_e_XGHxxKo',
    appId: '1:699728181193:android:e9383a59f5ec32111ada18',
    messagingSenderId: '699728181193',
    projectId: 'chat-app-63df9',
    storageBucket: 'chat-app-63df9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1VYQr2VY7JJFQtRsw3yWUJYbDopbb3Kg',
    appId: '1:699728181193:ios:ac68e029a9607ab11ada18',
    messagingSenderId: '699728181193',
    projectId: 'chat-app-63df9',
    storageBucket: 'chat-app-63df9.appspot.com',
    androidClientId: '699728181193-b7j9ojmqtphokmjvggila630120502r4.apps.googleusercontent.com',
    iosClientId: '699728181193-8r5ip0u8kpqc9jloqnn4b3n7gj23q8vl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1VYQr2VY7JJFQtRsw3yWUJYbDopbb3Kg',
    appId: '1:699728181193:ios:9bc59438dd697e351ada18',
    messagingSenderId: '699728181193',
    projectId: 'chat-app-63df9',
    storageBucket: 'chat-app-63df9.appspot.com',
    androidClientId: '699728181193-b7j9ojmqtphokmjvggila630120502r4.apps.googleusercontent.com',
    iosClientId: '699728181193-jd9q4j93rhd0fpjeiupejupc7iqlqvd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
